### ISSUE TITLE
Use environment variables to configure the front application

### ISSUE THREAD

**Issue by damien-carcel** [damien-carcel/app-skeleton#113]
Right now, a configuration file `config/api.json` is used to configure the front-end application.

- The routes should be hard-coded in the containers, and the back-end application updated so the routes are the same than with the `json-server` used for development.
- The rest of the configuration:
    ```YAML
    "protocol": "http",
    "host": "nginx-back",
    "port": 80,
    ```
    should be one environment variable, setup in the system or in the containers.
