### ISSUE TITLE
Remove the use of chromedriver for End to End tests

### ISSUE THREAD

**Issue by damien-carcel** [damien-carcel/app-skeleton#130]
Since https://github.com/damien-carcel/app-skeleton/issues/124, End to End tests are using Chrome and the chromedriver, directly controlled from Behat Mink thanks to `dmore/behat-chrome-extension`.
For a simple configuration and usage, Chrome is currently installed directly in the `fpm` image. 

However, this is not a good solution, and it should have its own dedicated image. ~The chosen solution is to use Selenium with Chrome in headless mode. Even if it is slower (benchmark and configuration are provided in the comment below), it is way easier to use, both locally and with Docker (no more Chrome to launch, Selenium do it for us).~

As the back-end application is a full REST API, it doesn't need a real web browser. The BrowserKitDriver used by default by the Mink extension (that was used previously) is enough. Test inside a real web browser will be performed on the front-end application, with CucumberJS and Chrome headless.

- Remove `dmore/behat-chrome-extension`~, install and configure `behat/mink-selenium2-driver`~
- Update the documentation
- Update Travis configuration

**Comment by damien-carcel** [comment]
Using selenium work out of the box with the latest Docker images for Chrome Standalone. 
However, tests are running slower. Just on 1 test:
- Chrome remote debug headless: ~8 ms
- Selenium 3 with Chrome headless: ~30 ms
- Selenium 3 with Chrome (with its UI): ~50ms

To use Selenium:

```bash
composer require --dev behat/mink-selenium2-driver
```
Then use the following configuration:
```yaml
end-to-end:
    extensions:
        Behat\MinkExtension:
            sessions:
                default:
                    selenium2:
                        browser: 'chrome'
                        wd_host: 'http://selenium:4444/wd/hub'
                        capabilities:
                            chrome:
                                switches:
                                - '--headless'
                                - '--disable-gpu'
                                - '--window-size=1920,1080'
                                - '--no-sandbox'
```
Like the `base_url`, `wd_host` should be an environment variable.
