### ISSUE TITLE
Move Docker Compose to Traefik 2

### ISSUE THREAD

**Issue by damien-carcel** [damien-carcel/app-skeleton#216]
- Use Traefik 2 new labels
  ```
  services:
    api:
        labels:
            - 'traefik.http.routers.api.rule=Host(`skeleton-api.docker.local`)'
  ```
- Write documentation for that => create a dedicated repository
